apiVersion: apps/v1
kind: Deployment
metadata:
  name: swisshousing-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swisshousing-app
  template:
    metadata:
      labels:
        app: swisshousing-app
    spec:
      containers:
      - name: swisshousing-app
        image: bokica08/devops-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://swisshousing-db:5432/swisshousing
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_JPA_SHOW_SQL
      imagePullSecrets:
      - name: regcred
