name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: swiss
          POSTGRES_PASSWORD: dians
          POSTGRES_DB: swisshousing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      -
        name: Wait for PostgreSQL to start
        run: sleep 10
      -
        name: Build with Maven
        run: |
          cd backend
          mvn clean package -Dspring.profiles.active=prod
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Stop existing containers
        run: docker-compose down

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
