name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend with Maven
        run: |
          cd backend
          mvn clean package -Dspring.profiles.active=prod

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: bokica08/devops-backend:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml up -d
