name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: swiss
          POSTGRES_PASSWORD: dians
          POSTGRES_DB: swisshousing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      -
        name: Wait for PostgreSQL to start
        run: sleep 10
      -
        name: Build with Maven
        run: |
          cd backend
          mvn clean package -Dspring.profiles.active=prod
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: bokica08/devops-backend:latest 

  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./dians-front-end/
          file: ./dians-front-end/Dockerfile
          push: true
          tags: bokica08/devops-frontend:latest
          
  deploy:
    needs: [backend, frontend]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Connect to Kubernetes
        run: |
          kubectl config use-context k3d-kube4
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f configMap.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f deployment-front.yaml
          kubectl apply -f statefullSet.yaml
          kubectl apply -f service-db.yaml
          kubectl apply -f service.yaml
          kubectl apply -f service-front.yaml
          kubectl apply -f ingress.yaml


